title: My First GitHub Page
author: Sanatan Prasad
theme: minima
email: sanatan.prasad@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Avid learner.

# social links
twitter_username: sanatan22 # DO NOT include the @ character, or else the build will fail!
github_username:  sanatan22 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
